final updates to code magic .yaml file

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,7 +1,7 @@
 definitions:
   env_vars: &env_vars
     FIREBASE_PROJECT_ID: your-firebase-project-id
-    ASSETS_URL: your-assets-url-for-client # URL to zip file containing the client-specific assets including google services files
+    BASE_ASSETS_URL: your-base-assets-url # Base URL for assets, excluding the specific filename
 
   scripts:
     - &get_assets
@@ -9,13 +9,19 @@ definitions:
       script: |
         # Ensure Firebase CLI is installed
         curl -sL https://firebase.tools | bash
-
+        
         # Authenticate with Firebase
         firebase login:ci --token $FIREBASE_TOKEN
+        
+        # Dynamic asset file name based on CLIENT_ID
+        ASSET_FILE_NAME="assets_${CLIENT_ID}.zip"
+        
+        # Construct the full URL for the assets file
+        ASSETS_URL="${BASE_ASSETS_URL}/${ASSET_FILE_NAME}"
 
         # Download client-specific assets
-        echo "Downloading assets for ${CLIENT_ID}"
-        curl -o client_assets.zip $ASSETS_URL || echo "Failed to download client assets"
+        echo "Downloading assets from ${ASSETS_URL}"
+        curl -o client_assets.zip $ASSETS_URL || echo "Failed to download ${ASSET_FILE_NAME}"
         unzip client_assets.zip -d ./assets
 
     - name: Replace assets, .env, and Google services files
@@ -24,7 +30,7 @@ definitions:
         cp ./assets/images/app_launcher_icon.png ./android/app/src/main/res/mipmap/
         cp ./assets/images/app_launcher_icon.png ./ios/Runner/Assets.xcassets/AppIcon.appiconset/
         cp ./assets/images/error_image.png ./assets/images/
-
+        
         # Replace Google services files
         cp ./assets/android/google-services.json ./android/app/
         cp ./assets/ios/GoogleService-Info.plist ./ios/Runner/
@@ -52,7 +58,7 @@ workflows:
 
       - name: Install dependencies
         script: flutter packages pub get
-
+      
       - name: Flutter build ipa and automatic versioning
         script: |
           BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
