final updates

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -40,20 +40,28 @@ workflows:
         FIREBASE_TOKEN: your-firebase-ci-token
         APP_NAME: "Default App Name"
         BUNDLE_ID: "com.example.app"
-    scripts:
-      - name: Download and unpack client-specific assets
-        script: |
-          echo "Downloading assets from ${ASSETS_URL}"
-          curl -o "assets_${CLIENT_ID}.zip" "${ASSETS_URL}" || echo "Failed to download assets_${CLIENT_ID}.zip"
-          unzip "assets_${CLIENT_ID}.zip" -d ./assets
-      - name: Replace assets, .env, and Google services files
-        script: |
-          cp ./assets/images/app_launcher_icon.png ./android/app/src/main/res/mipmap/
-          cp ./assets/images/app_launcher_icon.png ./ios/Runner/Assets.xcassets/AppIcon.appiconset/
-          cp ./assets/images/error_image.png ./assets/images/
-          cp ./assets/android/google-services.json ./android/app/
-          cp ./assets/ios/GoogleService-Info.plist ./ios/Runner/
-          cp ./assets/client/client.env ./assets/
+  scripts:
+    - &get_assets
+      name: Download and unpack client-specific assets
+      script: |
+        echo "Downloading assets from ${ASSETS_URL}"
+        curl -o "assets_${CLIENT_ID}.zip" "${ASSETS_URL}" || echo "Failed to download assets_${CLIENT_ID}.zip"
+        echo "Removing old assets and replacing with new ones"
+        rm -rf ./assets/   # This removes the existing assets directory
+        unzip "assets_${CLIENT_ID}.zip" -d ./assets  # Unzip directly to the target directory
+
+    - name: Update assets and configuration
+      script: |
+        # Update Google services files and .env
+        cp ./assets/android/google-services.json ./android/app/
+        cp ./assets/ios/GoogleService-Info.plist ./ios/Runner/
+        cp ./assets/client/client.env ./assets/
+
+        # Ensure all packages are fetched
+        flutter pub get
+
+        # Update app icons using flutter_launcher_icons
+        flutter pub run flutter_launcher_icons
       - name: Change iOS app name
         script: |
           /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" -c "Set :CFBundleDisplayName $APP_NAME" ios/${XCODE_SCHEME}/Info.plist
